pub mod client;
pub mod types;
pub mod notes_repo;
pub mod embeddings_repo;
pub mod entities_repo;
pub mod self_model_repo;
pub mod goals_repo;
pub mod beliefs_repo;
pub mod dispatch_repo;
pub mod sessions_repo;

pub use client::{SqliteClient, SqliteError};
pub use types::*;
pub use notes_repo::NotesRepo;
pub use embeddings_repo::EmbeddingsRepo;
pub use entities_repo::{EntitiesRepo, normalize_alias};
pub use self_model_repo::SelfModelRepo;
pub use goals_repo::GoalsRepo;
pub use beliefs_repo::BeliefsRepo;
pub use dispatch_repo::{DispatchRepo, DispatchTaskRow};
pub use sessions_repo::{SessionsRepo, IndexedSession};
