pub mod beliefs_repo;
pub mod client;
pub mod communities;
pub mod dispatch_repo;
pub mod embeddings_repo;
pub mod goals_repo;
pub mod memvid_replay_offset_repo;
pub mod notes_repo;
pub mod notions_repo;
pub mod qq_binding_repo;
pub mod self_model_repo;
pub mod sessions_repo;
pub mod traits;
pub mod types;

pub use beliefs_repo::BeliefsRepo;
pub use client::{SqliteClient, SqliteError, probe_latest_version};
pub use communities::{Adjacency, louvain_communities};
pub use dispatch_repo::{DispatchRepo, DispatchTaskRow};
pub use embeddings_repo::EmbeddingsRepo;
pub use goals_repo::GoalsRepo;
pub use memvid_replay_offset_repo::MemvidReplayOffsetRepo;
pub use notes_repo::NotesRepo;
pub use notions_repo::{NotionsRepo, normalize_alias};
pub use qq_binding_repo::{QqBindingRepo, QqBindingRow};
pub use self_model_repo::SelfModelRepo;
pub use sessions_repo::{IndexedSession, SessionsRepo};
pub use traits::notions::NotionsRepository;
pub use workflow_repo::{TaskCheckpoint, WorkflowPlanRow, WorkflowRepo, WorkflowTaskRow};
pub mod workflow_repo;
pub use types::*;
