[package]
name = "zen"
version = "0.0.1"
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
description.workspace = true

[[bin]]
name = "zen"
path = "src/main.rs"

[package.metadata.dist]
formula = "zenspace"

[dependencies]
zen-cli = { path = "../zen-cli" }
zen-core = { path = "../zen-core" }
dotenvy = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
