use chrono::NaiveDate;
use zen_core::paths::ZenPaths;

/// Briefing data assembled from knowledge-base state.
#[derive(Debug, Clone)]
pub struct Briefing {
    pub date: NaiveDate,
    pub pending_notes: usize,
    pub today_log_entries: usize,
    pub pending_habits: Vec<String>,
    pub active_goals: Vec<String>,
    pub contradictions: usize,
    pub recommended_actions: Vec<String>,
}

/// Generate a daily briefing by reading current state from the
/// `~/.zen/` directories.
///
/// This is a lightweight, **offline-first** operation — it reads
/// existing files and derives a summary without calling any LLM.
pub fn generate_briefing(zen_paths: &ZenPaths) -> Result<Briefing, anyhow::Error> {
    let today = chrono::Utc::now().naive_utc().date();

    let pending_notes = count_files_in(&zen_paths.inbox())?;
    let today_log_entries = count_today_log_entries(zen_paths, today)?;
    let (pending_habits, active_goals) = read_habits_and_goals(zen_paths)?;
    let contradictions = count_contradictions(zen_paths)?;

    let recommended_actions = derive_recommendations(
        pending_notes,
        today_log_entries,
        &pending_habits,
        contradictions,
    );

    Ok(Briefing {
        date: today,
        pending_notes,
        today_log_entries,
        pending_habits,
        active_goals,
        contradictions,
        recommended_actions,
    })
}

/// Render a [`Briefing`] as markdown.
pub fn render_briefing_md(briefing: &Briefing) -> String {
    let mut out = String::new();

    out.push_str(&format!(
        "# Daily Briefing — {}\n\n",
        briefing.date.format("%Y-%m-%d")
    ));

    out.push_str("## Overview\n\n");
    out.push_str(&format!(
        "- Inbox notes pending: **{}**\n",
        briefing.pending_notes
    ));
    out.push_str(&format!(
        "- Today's log entries: **{}**\n",
        briefing.today_log_entries
    ));
    out.push_str(&format!(
        "- Unresolved contradictions: **{}**\n",
        briefing.contradictions
    ));

    if !briefing.pending_habits.is_empty() {
        out.push_str("\n## Pending Habits\n\n");
        for h in &briefing.pending_habits {
            out.push_str(&format!("- [ ] {h}\n"));
        }
    }

    if !briefing.active_goals.is_empty() {
        out.push_str("\n## Active Goals\n\n");
        for g in &briefing.active_goals {
            out.push_str(&format!("- {g}\n"));
        }
    }

    if !briefing.recommended_actions.is_empty() {
        out.push_str("\n## Recommended Actions\n\n");
        for (i, a) in briefing.recommended_actions.iter().enumerate() {
            out.push_str(&format!("{}. {a}\n", i + 1));
        }
    }

    out.push_str("\n---\n*Generated by `zen brief` · Zen agentic workspace*\n");

    out
}

/// Persist the briefing markdown to `~/.zen/output/brief-YYYY-MM-DD.md`.
pub fn save_briefing(zen_paths: &ZenPaths, md: &str) -> Result<std::path::PathBuf, anyhow::Error> {
    let output_dir = zen_paths.output();
    std::fs::create_dir_all(&output_dir)?;

    let date = chrono::Utc::now().naive_utc().date();
    let path = output_dir.join(format!("brief-{}.md", date.format("%Y-%m-%d")));

    std::fs::write(&path, md)?;
    Ok(path)
}

// ─── Private helpers ────────────────────────────────────────────────────

fn count_files_in(dir: &std::path::Path) -> Result<usize, anyhow::Error> {
    if !dir.is_dir() {
        return Ok(0);
    }
    let count = std::fs::read_dir(dir)?
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.path()
                .extension()
                .is_some_and(|ext| ext == "md" || ext == "txt")
        })
        .count();
    Ok(count)
}

fn count_today_log_entries(zen_paths: &ZenPaths, date: NaiveDate) -> Result<usize, anyhow::Error> {
    let year = date.format("%Y").to_string();
    let year_dir = zen_paths.memory().join(&year);
    let file = year_dir.join(format!("{}.md", date.format("%Y-%m-%d")));

    if !file.is_dir() && file.exists() {
        let content = std::fs::read_to_string(&file)?;
        let entries = content.lines().filter(|l| l.starts_with("## ")).count();
        Ok(entries)
    } else {
        Ok(0)
    }
}

fn read_habits_and_goals(
    zen_paths: &ZenPaths,
) -> Result<(Vec<String>, Vec<String>), anyhow::Error> {
    let mut pending_habits = Vec::new();
    let mut active_goals = Vec::new();

    // Read habits.toml if present
    let habits_path = zen_paths.global_root().join("habits.toml");
    if habits_path.exists() {
        let content = std::fs::read_to_string(&habits_path)?;
        if let Ok(config) = toml::from_str::<toml::Value>(&content)
            && let Some(habits) = config.get("habits").and_then(|h| h.as_array())
        {
            for habit in habits {
                if let Some(done) = habit.get("done").and_then(|d| d.as_bool())
                    && !done
                    && let Some(name) = habit.get("name").and_then(|n| n.as_str())
                {
                    pending_habits.push(name.to_string());
                }
            }
        }
    }

    // Read goals.toml if present
    let goals_path = zen_paths.global_root().join("goals.toml");
    if goals_path.exists() {
        let content = std::fs::read_to_string(&goals_path)?;
        if let Ok(config) = toml::from_str::<toml::Value>(&content)
            && let Some(goals) = config.get("goals").and_then(|g| g.as_array())
        {
            for goal in goals {
                if let Some(status) = goal.get("status").and_then(|s| s.as_str()) {
                    if (status == "active" || status == "in_progress")
                        && let Some(name) = goal.get("name").and_then(|n| n.as_str())
                    {
                        active_goals.push(name.to_string());
                    }
                } else if goal.get("name").is_some()
                    && let Some(name) = goal.get("name").and_then(|n| n.as_str())
                {
                    active_goals.push(name.to_string());
                }
            }
        }
    }

    Ok((pending_habits, active_goals))
}

fn count_contradictions(zen_paths: &ZenPaths) -> Result<usize, anyhow::Error> {
    // Read contradiction records from knowledge/contradictions/ if present.
    let contra_dir = zen_paths
        .vault()
        .join("consolidate")
        .join("contradictions");
    if !contra_dir.is_dir() {
        return Ok(0);
    }
    let count = std::fs::read_dir(&contra_dir)?
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.path()
                .extension()
                .is_some_and(|ext| ext == "md" || ext == "json")
        })
        .count();
    Ok(count)
}

fn derive_recommendations(
    pending_notes: usize,
    today_log_entries: usize,
    pending_habits: &[String],
    contradictions: usize,
) -> Vec<String> {
    let mut actions = Vec::new();

    if pending_notes > 0 {
        actions.push(format!(
            "Process {pending_notes} pending inbox notes for consolidation"
        ));
    }

    if today_log_entries == 0 {
        actions.push("No log entries today — consider recording what you did".to_string());
    }

    if !pending_habits.is_empty() {
        actions.push(format!(
            "{} pending habit{} to review (e.g. habits.toml)",
            pending_habits.len(),
            if pending_habits.len() == 1 { "" } else { "s" }
        ));
    }

    if contradictions > 0 {
        actions.push(format!(
            "{contradictions} unresolved contradiction{} — review via `zen lint run`",
            if contradictions == 1 { "" } else { "s" }
        ));
    }

    if actions.is_empty() {
        actions.push("Everything looks clean — no pending items".to_string());
    }

    actions
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_render_briefing_minimal() {
        let briefing = Briefing {
            date: NaiveDate::from_ymd_opt(2026, 5, 26).unwrap(),
            pending_notes: 0,
            today_log_entries: 2,
            pending_habits: Vec::new(),
            active_goals: Vec::new(),
            contradictions: 0,
            recommended_actions: vec!["Everything looks clean".to_string()],
        };
        let md = render_briefing_md(&briefing);
        assert!(md.contains("Daily Briefing — 2026-05-26"));
        assert!(md.contains("Inbox notes pending: **0**"));
        assert!(md.contains("Everything looks clean"));
    }

    #[test]
    fn test_derive_recommendations_empty() {
        let actions = derive_recommendations(0, 1, &[], 0);
        assert_eq!(actions, vec!["Everything looks clean — no pending items"]);
    }

    #[test]
    fn test_derive_recommendations_finds_items() {
        let actions = derive_recommendations(5, 0, &["exercise".to_string()], 2);
        assert!(actions.iter().any(|a| a.contains("5 pending inbox notes")));
        assert!(actions.iter().any(|a| a.contains("No log entries today")));
        assert!(actions.iter().any(|a| a.contains("pending habit")));
        assert!(
            actions
                .iter()
                .any(|a| a.contains("unresolved contradictions"))
        );
    }
}
