use clap::Subcommand;
use colored::Colorize;
use std::fs;
use tracing::debug;

use zen_core::errors::ZenError;
use zen_core::paths::ZenPaths;

// ---------------------------------------------------------------------------
// Workspace subcommands (FR-003, FR-004, FR-005)
// ---------------------------------------------------------------------------

#[derive(Subcommand)]
pub enum WorkspaceCommands {
    /// Initialize a workspace (.zen directory structure)
    Init {
        /// Target directory (defaults to current directory)
        #[arg(short, long)]
        path: Option<String>,
    },
    /// Show workspace status (directories, config)
    Status,
    /// Cleanup workspace artifacts (cache, temp files)
    Cleanup {
        /// Dry-run: show what would be cleaned
        #[arg(short, long, action)]
        dry_run: bool,
    },
}

pub fn execute_command(operation: &WorkspaceCommands) -> Result<(), ZenError> {
    match operation {
        WorkspaceCommands::Init { path } => {
            let target = path.as_deref().unwrap_or(".");
            let zen_dir = format!("{}/.zen", target);
            debug!("initializing workspace at: {}", zen_dir);

            // Create .zen/ directory structure (FR-003, FR-004)
            let dirs = &[
                "knowledge/inbox",
                "knowledge/raw",
                "knowledge/wiki",
                "sessions",
                "skills",
                "finance",
                "memory",
            ];

            if fs::metadata(&zen_dir).is_ok() {
                println!(
                    "{} Workspace already initialized at {}",
                    "ℹ".bright_blue().bold(),
                    zen_dir.cyan().bold()
                );
            } else {
                fs::create_dir_all(&zen_dir)?;
                for dir in dirs {
                    let full = format!("{}/{}", zen_dir, dir);
                    fs::create_dir_all(&full)?;
                    println!("  {} {}", "✓".green().bold(), full.dimmed());
                }

                // Initialize empty config
                let config_path = format!("{}/config.toml", zen_dir);
                if !std::path::Path::new(&config_path).exists() {
                    let default_config =
                        "# Zen Workspace Configuration\n# Generated by `zen workspace init`\n\n";
                    fs::write(&config_path, default_config)?;
                }

                println!(
                    "\n{} Workspace initialized at {}",
                    "🏗".bright_yellow().bold(),
                    zen_dir.cyan().bold()
                );
            }

            Ok(())
        }
        WorkspaceCommands::Status => {
            debug!("showing workspace status");
            let paths = ZenPaths::detect().ok();

            println!("{}", "📂 Workspace Status".bold());

            match &paths {
                Some(p) => {
                    println!(
                        "  Global root: {}",
                        p.global_root().display().to_string().cyan()
                    );
                    match p.workspace_root() {
                        Some(w) => println!("  Workspace root: {}", w.display().to_string().cyan()),
                        None => println!(
                            "  Workspace root: {}",
                            "(not found — no .zen/ in parent dirs)".yellow()
                        ),
                    }
                    println!(
                        "  Config file: {}",
                        p.config_file().display().to_string().dimmed()
                    );
                }
                None => {
                    println!("  Home directory: {}", "not found".red().bold());
                }
            }

            Ok(())
        }
        WorkspaceCommands::Cleanup { dry_run } => {
            debug!("cleaning workspace (dry_run={})", dry_run);
            println!(
                "{} Workspace cleanup{}",
                "🧹".bright_red().bold(),
                if *dry_run {
                    " (dry run)".yellow().to_string()
                } else {
                    String::new()
                }
            );
            println!(
                "{}",
                "  (Service-layer workspace cleanup deferred to zen-service)".dimmed()
            );
            Ok(())
        }
    }
}
