name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Install ripgrep
        uses: taiki-e/install-action@v2
        with:
          tool: ripgrep
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - name: Run lint
        run: bin/lint
      - name: Run tests
        run: bin/test

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Install ripgrep
        uses: taiki-e/install-action@v2
        with:
          tool: ripgrep
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - name: Build
        run: bin/build
      - name: Run tests
        run: bin/test
      - name: Run lint
        run: bin/lint